### ISSUE TITLE
how can I generate a docker imagine optimised?

### ISSUE THREAD

**Issue by rodrigorodrigues** [alina-yur/native-spring-boot#1]
Hi @alina-yur,

I'm following your sample and I could generate the _default.iprof_ now I'm wondering how can I generate a docker image using spring plugin, do you know if that's possible?

`mvn -Pnative spring-boot:build-image` 

```
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <configuration>
                    <buildArgs>
                        <buildArg>--pgo=default.iprof</buildArg>
                        <buildArg>--gc=G1</buildArg>
                    </buildArgs>
                </configuration>
            </plugin>
```

**Comment by alina-yur** [comment]
hi @rodrigorodrigues! Glad this silly example helps, didn't think anyone would stumble upon it:))

Yes you can totally build an image with `mvn -Pnative spring-boot:build-image`. Now the question is where and how you can collect profiles, so they are representative of your production workload. If you can emulate production workload locally, you can build an optimized image locally. If relevant workload is only available in production, it could be necessary to deploy an instrumented image, collect profiles, and then rebuild with those profiles.

**Comment by rodrigorodrigues** [comment]
closing this issue here the conversation continue on https://github.com/rodrigorodrigues/rinha-de-backend-2024-q1-javaslow-spring/issues/1
