### ISSUE TITLE
HI,

### ISSUE THREAD

**Issue by steveGuRen** [alina-yur/native-spring-boot#3]
I am a beginner in GraalVM and currently in the testing phase. Could you please share some resources on setting up projects and learning materials? Thank you~
I am very inexperienced in GraalVM.

**Comment by alina-yur** [comment]
Hi @steveGuRen, you can check out those resources: [alina-yur.github.io/graalvm-resources](https://alina-yur.github.io/graalvm-resources/)
Particularly interesting I would say would be https://www.graalvm.org/latest/guides/ and https://github.com/graalvm/graalvm-demos. 
You can also clone this repo: https://github.com/alina-yur/native-spring-boot and follow the steps in the README.

Hope this helps,
Alina
